const { Quiz } = require('../models');
const sequelize = require('../config/connection');



const QuizData = [
  {
    category: "General Knowledge",
    correctAnswer: "A Lamb",
    answerA: "A Lamb",
    answerB: "A Puppy",
    answerC: "A Fish",
    answerD: "A Swan",
    question:
      "In the nursery rhyme, what animal belonged to a girl named Mary?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Afghani",
    answerA: "Afghani",
    answerB: "Rial",
    answerC: "Dinar",
    answerD: "Derum",
    question: "What is the basic unit of currency for Afghanistan?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Valetudinarian",
    answerA: "Valetudinarian",
    answerB: "Fudgel",
    answerC: "Lackadaisical",
    answerD: "Groke",
    question:
      "Which word is defined as 'a sickly or weak person, especially one who is constantly and morbidly concerned with his or her health'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "The d in 'door'",
    answerA: "The d in 'door'",
    answerB: "The y in 'yellow'",
    answerC: "The r in 'red'",
    answerD: "The z in 'zoo'",
    question: "In phonetics, which of these is an example of a plosive sound?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "8",
    answerA: "8",
    answerB: "12",
    answerC: "10",
    answerD: "6",
    question: "How Many Furlongs Are There In A Mile?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "China",
    answerA: "China",
    answerB: "Greece",
    answerC: "The USA",
    answerD: "Britain",
    question:
      "In which country was natural gas first used as a source of energy?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "South Pole",
    answerA: "South Pole",
    answerB: "The Peak of Mount Everest",
    answerC: "The Moon",
    answerD: "The Mariana Trench",
    question: "In 1911 Roald Amundsen became the first person to reach where?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Ernest Wiseman",
    answerA: "Ernest Wiseman",
    answerB: "Jeffrey Wallis",
    answerC: "Lars Friedel",
    answerD: "Matthew Flaunt",
    question: "What was the real name of Eric Morecambes partner?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Woebegone",
    answerA: "Woebegone",
    answerB: "Ratoon",
    answerC: "Dragoman",
    answerD: "Bobsy-die",
    question: "Which word is defined as 'sad or miserable in appearance'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Obelus",
    answerA: "Obelus",
    answerB: "Gibberish",
    answerC: "Donkey Engine",
    answerD: "Taradiddle",
    question: "Which word is defined as 'the symbol ÷'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Dipthong",
    answerA: "Dipthong",
    answerB: "Kakorrhaphiophobia",
    answerC: "Grommet",
    answerD: "Jentacular",
    question:
      "Which word is defined as 'two vowel sounds joined in one syllable to form one speech sound, e.g. the sounds of “ou” in out and of “oy” in boy'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Sherwood forest",
    answerA: "Sherwood forest",
    answerB: "Nottingham",
    answerC: "Bedgebury Forest",
    answerD: "Hoodwood",
    question: "Where did Robin Hood supposedly live?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Juliett",
    answerA: "Juliett",
    answerB: "Jump",
    answerC: "Jericho",
    answerD: "Jolly",
    question:
      "What word is used in the NATO Phonetic Alphabet for the letter J?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "LXIX",
    answerA: "LXIX",
    answerB: "CXIX",
    answerC: "LIXX",
    answerD: "CIXX",
    question: "How do you write 69 in Roman numerals?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Smicker",
    answerA: "Smicker",
    answerB: "Whiffler",
    answerC: "Gardyloo",
    answerD: "Widdershins",
    question: "Which word is defined as 'to look amorously after somebody'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "The n in 'no'",
    answerA: "The n in 'no'",
    answerB: "The d in 'door'",
    answerC: "The v in 'village'",
    answerD: "The g in 'green'",
    question: "In phonetics, which of these is an example of a nasal sound?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Pastern",
    answerA: "Pastern",
    answerB: "Sole",
    answerC: "Periople",
    answerD: "Hock",
    question:
      "The part of the foot of a horse between the fetlock and the hoof is the __________",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Snickersnee",
    answerA: "Snickersnee",
    answerB: "Curmudgeon",
    answerC: "Xertz",
    answerD: "Cattywampus",
    question:
      "Which word is defined as 'to engage in cut-and-thrust fighting with knives'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Conjubilant",
    answerA: "Conjubilant",
    answerB: "Jentacular",
    answerC: "Discombobulate",
    answerD: "Whippersnapper",
    question: "Which word is defined as 'shouting together with joy'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Discombobulate",
    answerA: "Discombobulate",
    answerB: "Cacophony",
    answerC: "Dragoman",
    answerD: "Dragoman",
    question: "Which word is defined as 'to disconcert of confuse'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Water",
    answerA: "Water",
    answerB: "Jungle",
    answerC: "Desert",
    answerD: "Arctic",
    question: "In What Environment Did Ichthysaurs Live",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Bonsai",
    answerA: "Bonsai",
    answerB: "Ornamental Shrubbery",
    answerC: "Decorage",
    answerD: "Topiary",
    question:
      "What is the name given to the art of miniaturising trees and maintaining their small size?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Cacophony",
    answerA: "Cacophony",
    answerB: "Cabotage",
    answerC: "Gardyloo",
    answerD: "Halfpace",
    question:
      "Which word is defined as 'a harsh, discordant mixture of sounds'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Washington DC",
    answerA: "Washington DC",
    answerB: "New York City",
    answerC: "Brussels",
    answerD: "Geneva",
    question: "Where is Capitol Hill?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Romeo",
    answerA: "Romeo",
    answerB: "Rwanda",
    answerC: "Roar",
    answerD: "Rowboat",
    question:
      "What word is used in the NATO Phonetic Alphabet for the letter R?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Quire",
    answerA: "Quire",
    answerB: "Whiffler",
    answerC: "Ragamuffin",
    answerD: "Ragamuffin",
    question: "Which word is defined as 'two dozen sheets of paper'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "The Hoover Dam",
    answerA: "The Hoover Dam",
    answerB: "The Three Gorges Dam",
    answerC: "The Oroville Dam",
    answerD: "The Theodore Roosevelt Dam",
    question: "Which Dam Harnesses The Colorado River",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Amerigo Vespucci",
    answerA: "Amerigo Vespucci",
    answerB: "Aymeric Santiago",
    answerC: "Merica Bonnuci",
    answerD: "Amir Icarlo",
    question: "After whom was America named?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "China",
    answerA: "China",
    answerB: "England",
    answerC: "France",
    answerD: "Russia",
    question: "Which nation invented Paper?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Foal",
    answerA: "Foal",
    answerB: "Tiger",
    answerC: "Kitten",
    answerD: "Giraffe",
    question: "What is the meaning of the name of the constellation Equuleus?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "The Netherlands ",
    answerA: "The Netherlands ",
    answerB: "Belgium",
    answerC: "Sweden",
    answerD: "Spain",
    question: "KLM Is The National Airline Of Which Country?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Agastopia",
    answerA: "Agastopia",
    answerB: "Dragoman",
    answerC: "Oxter",
    answerD: "Jentacular",
    question:
      "Which word is defined as 'admiration of a particular part of someone’s body'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Erf",
    answerA: "Erf",
    answerB: "Billingsgate",
    answerC: "Taradiddle",
    answerD: "Blatherskite",
    question: "Which word is defined as 'a plot of land'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "New Mexico",
    answerA: "New Mexico",
    answerB: "Nagasaki",
    answerC: "Hiroshima",
    answerD: "Bikini Atoll",
    question: "Where did the first atomic bomb explode?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Whiffler",
    answerA: "Whiffler",
    answerB: "Firman",
    answerC: "Salopettes",
    answerD: "Donkey Engine",
    question:
      "Which word is defined as 'somebody who walks in front of you through a crowd'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "The y in 'yellow'",
    answerA: "The y in 'yellow'",
    answerB: "The p in 'pin'",
    answerC: "The t in 'train'",
    answerD: "The sh in 'shop'",
    question:
      "In phonetics, which of these is an example of an approximant sound?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "8 Maids A Milking",
    answerA: "8 Maids A Milking",
    answerB: "8 Lords a Leaping",
    answerC: "8 Swans a Swimming",
    answerD: "8 Jugglers Juggling",
    question:
      'What Did My True Love Give To Me On The "Eighth" Day Of Christmas"?',
  },
  {
    category: "General Knowledge",
    correctAnswer: "Tittynope",
    answerA: "Tittynope",
    answerB: "Funambulist",
    answerC: "Blatherskite",
    answerD: "Winklepicker",
    question:
      "Which word is defined as 'a small quantity of something left over'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Three",
    answerA: "Three",
    answerB: "Four",
    answerC: "Five",
    answerD: "Six",
    question: "How many astronauts manned each Apollo flight?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Bohemia",
    answerA: "Bohemia",
    answerB: "Prussia",
    answerC: "Silesia",
    answerD: "Moravia",
    question:
      'From the Christmas Carol "Good King Wenceslas", where was Good King Wenceslas the King of?',
  },
  {
    category: "General Knowledge",
    correctAnswer: "De Militarized Zone",
    answerA: "De Militarized Zone",
    answerB: "Definite Multivariate Zone",
    answerC: "Deregulated Monetary Zone",
    answerD: "Decompression Minimum Zone",
    question: "What does 'DMZ' stand for?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Curmudgeon",
    answerA: "Curmudgeon",
    answerB: "Bumfuzzle",
    answerC: "Borborygmus",
    answerD: "Deipnophobia",
    question: "Which word is defined as 'a bad-tempered person'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Foxtrot",
    answerA: "Foxtrot",
    answerB: "Forget",
    answerC: "Fail",
    answerD: "Felicity",
    question:
      "What word is used in the NATO Phonetic Alphabet for the letter F?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "fricative",
    answerA: "fricative",
    answerB: "plosive",
    answerC: "approximant",
    answerD: "nasal",
    question:
      "In phonetics, the z in 'zoo' is an example of what kind of sound?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Groke",
    answerA: "Groke",
    answerB: "Quomodocunquizing",
    answerC: "Nudiustertian",
    answerD: "Macrosmatic",
    question:
      "Which word is defined as 'an old Scots term meaning to look at somebody while they’re eating in the hope that they’ll give you some of their food'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Sprunt",
    answerA: "Sprunt",
    answerB: "Bumfuzzle",
    answerC: "Salopettes",
    answerD: "Kakorrhaphiophobia",
    question:
      "Which word is defined as 'an old Scottish word meaning to chase girls around among the haystacks after dark'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Yarborough",
    answerA: "Yarborough",
    answerB: "Octothorpe",
    answerC: "Grommet",
    answerD: "Pauciloquent",
    question:
      "Which word is defined as 'hand of cards containing no card above a nine'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Swan",
    answerA: "Swan",
    answerB: "Ring",
    answerC: "River",
    answerD: "Mountain",
    question: "What is the meaning of the name of the constellation Cygnus?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Bobsy-die",
    answerA: "Bobsy-die",
    answerB: "Groke",
    answerC: "Whippersnapper",
    answerD: "Tittynope",
    question: "Which word is defined as 'a great deal of fuss or trouble'?",
  },
  {
    category: "General Knowledge",
    correctAnswer: "Echo",
    answerA: "Echo",
    answerB: "Elton",
    answerC: "Elbow",
    answerD: "Enable",
    question:
      "What word is used in the NATO Phonetic Alphabet for the letter E?",
  },
  {
    category: "Science",
    correctAnswer: "The North Star",
    answerA: "The North Star",
    answerB: "Orion's Belt",
    answerC: "The Sun",
    answerD: "Alpha Centauri",
    question: "As what is Polaris also known?",
  },
  {
    category: "Science",
    correctAnswer: "It faces backwards",
    answerA: "It faces backwards",
    answerB: "It is on their head",
    answerC: "It is detachable",
    answerD: "Both males and females have it",
    question: "What is an unusual feature of the wombat's pouch?",
  },
  {
    category: "Science",
    correctAnswer: "Cloud",
    answerA: "Cloud",
    answerB: "Planet",
    answerC: "Island",
    answerD: "Volcano",
    question: "Cirrus and Cumulus are types of what?",
  },
  {
    category: "Science",
    correctAnswer: "A Piglet",
    answerA: "A Piglet",
    answerB: "A Maggot",
    answerC: "A Cygnet",
    answerD: "A Colt",
    question: "What is the word for a young pig?",
  },
  {
    category: "Science",
    correctAnswer: "Seat Belt",
    answerA: "Seat Belt",
    answerB: "Cat Eye",
    answerC: "Airbag",
    answerD: "Crumple Zone",
    question:
      "What Vehicular Safety Device Was First Pantented By Ej Claghorn?",
  },
  {
    category: "Science",
    correctAnswer: "A shoal",
    answerA: "A shoal",
    answerB: "A host",
    answerC: "A murder",
    answerD: "A kindle",
    question: "What is the word for a group of herrings?",
  },
  {
    category: "Science",
    correctAnswer: "Geology",
    answerA: "Geology",
    answerB: "Astronomy",
    answerC: "Magnetism",
    answerD: "Meteorology",
    question:
      "What is the name of the science that studies the origin, history, and structure of the Earth?",
  },
  {
    category: "Science",
    correctAnswer: "A Maggot",
    answerA: "A Maggot",
    answerB: "An Owlet",
    answerC: "A Hatchling",
    answerD: "A Caterpillar",
    question: "What is the word for a young fly?",
  },
  {
    category: "Science",
    correctAnswer: "0",
    answerA: "0",
    answerB: "3",
    answerC: "1",
    answerD: "6",
    question: "How many moons does Mercury have?",
  },
  {
    category: "Science",
    correctAnswer: "Rattlesnakes",
    answerA: "Rattlesnakes",
    answerB: "Spiders",
    answerC: "Frogs",
    answerD: "Beetles",
    question: "__________ gather in groups to sleep through the winter. ",
  },
  {
    category: "Science",
    correctAnswer: "Poisons",
    answerA: "Poisons",
    answerB: "Radiation",
    answerC: "Abstract Categorisation",
    answerD: "Venomous Animals",
    question: "What Is Toxicology The Study Of?",
  },
  {
    category: "Science",
    correctAnswer: "Hardness",
    answerA: "Hardness",
    answerB: "Thickness",
    answerC: "Conductivity",
    answerD: "Resistance",
    question: "What Is Moh's Scale A Measure Of?",
  },
  {
    category: "Science",
    correctAnswer: "0",
    answerA: "0",
    answerB: "1",
    answerC: "2",
    answerD: "3",
    question: "How Many Humps Has A Dromedary Camel Got?",
  },
  {
    category: "Science",
    correctAnswer: "pollen",
    answerA: "pollen",
    answerB: "musical instruments",
    answerC: "drugs",
    answerD: "study of refuse and trash",
    question: "What is Palynology the study of?",
  },
  {
    category: "Science",
    correctAnswer: "Mexico",
    answerA: "Mexico",
    answerB: "Russia",
    answerC: "China",
    answerD: "Australia",
    question: "From Which Country Does The Poinsettia Plant Originate",
  },
  {
    category: "Science",
    correctAnswer: "A Vixen",
    answerA: "A Vixen",
    answerB: "A Ewe",
    answerC: "A Hen",
    answerD: "A Doe",
    question: "What is the word for a female fox?",
  },
  {
    category: "Science",
    correctAnswer: "32",
    answerA: "32",
    answerB: "2",
    answerC: "50",
    answerD: "24",
    question: "How many teeth does thr average adult human have?",
  },
  {
    category: "Science",
    correctAnswer: "the effects of radiation upon living organisms",
    answerA: "the effects of radiation upon living organisms",
    answerB: "fossils of ancient life",
    answerC: "the art and career of using cosmetics to improve beauty",
    answerD:
      "though not an -ology, is a commemoration of a person's life at his/her funeral",
    question: "What is Actinobiology the study of?",
  },
  {
    category: "Science",
    correctAnswer: "Calcium carbonate",
    answerA: "Calcium carbonate",
    answerB: "Calcium sulphate dihydrate",
    answerC: "Iron Oxide",
    answerD: "Deuterium Oxide",
    question: "What chemical has the formula CaCO3?",
  },
  {
    category: "Science",
    correctAnswer: "Giovanni Schiaparelli",
    answerA: "Giovanni Schiaparelli",
    answerB: "Galileo Galiei",
    answerC: "Mary Ward",
    answerD: "John Herschel",
    question: 'Who was the first person to notice "canals" on Mars?',
  },
  {
    category: "Science",
    correctAnswer: "J. J. Thomson",
    answerA: "J. J. Thomson",
    answerB: "Albert Einstein",
    answerC: "Marie Curie",
    answerD: "Antoine Lavoisier",
    question: "Who discovered the electron?",
  },
  {
    category: "Science",
    correctAnswer: "books, printing, and publishing; also called Bibliography",
    answerA: "books, printing, and publishing; also called Bibliography",
    answerB:
      "the derivation of a persons character traits, by studying the shape of their skull",
    answerC:
      "a neologism for the Pilates method, a system of physical exercise",
    answerD: "prehistoric life",
    question: "What is Bibliology the study of?",
  },
  {
    category: "Science",
    correctAnswer: "Incisors",
    answerA: "Incisors",
    answerB: "Molars",
    answerC: "Premolars",
    answerD: "Slicers",
    question: "The teeth used for biting or cutting are known as _______.",
  },
  {
    category: "Science",
    correctAnswer:
      "the specialty in medicine that deals with diseases of the lungs and the respiratory tract",
    answerA:
      "the specialty in medicine that deals with diseases of the lungs and the respiratory tract",
    answerB: "fossil footprints, tracks and burrows",
    answerC: "classification",
    answerD: "the mathematical study of closeness and connectedness",
    question: "What is Pulmonology the study of?",
  },
  {
    category: "Science",
    correctAnswer: "the mathematical study of closeness and connectedness",
    answerA: "the mathematical study of closeness and connectedness",
    answerB:
      "periodic biological phenomena such as flowering, migration, breeding, etc",
    answerC:
      "a set of words and/or phrases, usually in relation to some particular canon or field of study",
    answerD:
      "handwriting for the purpose of analysing the character of the writer",
    question: "What is Topology the study of?",
  },
  {
    category: "Science",
    correctAnswer: "sleep",
    answerA: "sleep",
    answerB: "the effects of radiation upon living organisms",
    answerC:
      "is concerned with earth materials that can be utilized for economic and/or industrial purposes",
    answerD: "the eyes",
    question: "What is Hypnology the study of?",
  },
  {
    category: "Science",
    correctAnswer: "Amphibians",
    answerA: "Amphibians",
    answerB: "Mammals",
    answerC: "Reptiles",
    answerD: "Marsupials",
    question: "What are frogs?",
  },
  {
    category: "Science",
    correctAnswer: "TNT",
    answerA: "TNT",
    answerB: "QuickSilver",
    answerC: "Dry Ice",
    answerD: "Borax",
    question: "What is trinitrotoluene commonly known as?",
  },
  {
    category: "Science",
    correctAnswer: "A barren",
    answerA: "A barren",
    answerB: "A sounder",
    answerC: "A leap",
    answerD: "A flight",
    question: "What is the word for a group of mules?",
  },
  {
    category: "Science",
    correctAnswer: "Low Blood Sugar",
    answerA: "Low Blood Sugar",
    answerB: "High Cholesterol",
    answerC: "High Blood Sugar",
    answerD: "Low Cholesterol",
    question: "What Causes Hypoglycemia?",
  },
  {
    category: "Science",
    correctAnswer: "A Buck",
    answerA: "A Buck",
    answerB: "A Stallion",
    answerC: "A Ram",
    answerD: "A Boar",
    question: "What is a male kangaroo known as?",
  },
  {
    category: "Science",
    correctAnswer: "the study or exploration of caves",
    answerA: "the study or exploration of caves",
    answerB: "how to encrypt and decrypt secret messages",
    answerC: "methods",
    answerD: "methods",
    question: "What is Speleology the study of?",
  },
  {
    category: "Science",
    correctAnswer: "animals",
    answerA: "animals",
    answerB: "the lymph system and glands",
    answerC: "the nature of values and value judgements",
    answerD:
      "the mnemonic practice of writing sentences such that the numbers of letters in the words correspond to the consecutive digits of pi",
    question: "What is Zoology the study of?",
  },
  {
    category: "Science",
    correctAnswer: "Dodecagon",
    answerA: "Dodecagon",
    answerB: "Octagon",
    answerC: "Hexagon",
    answerD: "Triangle",
    question: "What is the name of a shape with twelve sides?",
  },
  {
    category: "Science",
    correctAnswer: "Galileo Galilei",
    answerA: "Galileo Galilei",
    answerB: "Nicolas Copernicus",
    answerC: "Thomas Edison",
    answerD: "Alexander Fleming",
    question: "Who invented the telescope?",
  },
  {
    category: "Science",
    correctAnswer: "Thomas Edison",
    answerA: "Thomas Edison",
    answerB: "Samuel Colt",
    answerC: "Henry Blair",
    answerD: "Elisha Otis",
    question: "Who Invented The Gramophone?",
  },
  {
    category: "Science",
    correctAnswer: "A litter",
    answerA: "A litter",
    answerB: "A field",
    answerC: "A sounder",
    answerD: "A watch",
    question: "What is the word for a group of pups?",
  },
  {
    category: "Science",
    correctAnswer: "Emperor",
    answerA: "Emperor",
    answerB: "King",
    answerC: "Gentoo",
    answerD: "Adelie",
    question: "What Is The Largest Species Of Penguin?",
  },
  {
    category: "Science",
    correctAnswer: "Tomato",
    answerA: "Tomato",
    answerB: "Garlic",
    answerC: "Onion",
    answerD: "Chili Pepper",
    question: "What Is Alicante A Variety Of?",
  },
  {
    category: "Science",
    correctAnswer: "Mercury",
    answerA: "Mercury",
    answerB: "Silver",
    answerC: "Iron",
    answerD: "Titanium",
    question: "Which Metal is Also Known As Quicksilver?",
  },
  {
    category: "Science",
    correctAnswer: "A nye",
    answerA: "A nye",
    answerB: "A sedge",
    answerC: "A parliament",
    answerD: "A clowder",
    question: "What is the word for a group of pheasants?",
  },
  {
    category: "Science",
    correctAnswer: "Lava",
    answerA: "Lava",
    answerB: "Ash",
    answerC: "Ignea",
    answerD: "Pertrite",
    question: "The molten material from a volcano is ________",
  },
  {
    category: "Science",
    correctAnswer: "Table Salt",
    answerA: "Table Salt",
    answerB: "QuickSilver",
    answerC: "Baking Soda",
    answerD: "Cream of tartar",
    question: "What is the common name for sodium chloride?",
  },
  {
    category: "Science",
    correctAnswer: "Laxative",
    answerA: "Laxative",
    answerB: "Analgesic",
    answerC: "Anti inflammatory",
    answerD: "Suppository",
    question:
      "What is the word for a medicine that hastens the emptying of the bowels?",
  },
  {
    category: "Science",
    correctAnswer: "Birch Tree",
    answerA: "Birch Tree",
    answerB: "Oak Tree",
    answerC: "Maple Tree",
    answerD: "Elm Tree",
    question: "Which type of tree is known for its silvery white bark?",
  },
  {
    category: "Science",
    correctAnswer: "A Sow",
    answerA: "A Sow",
    answerB: "A Worker",
    answerC: "A Doe",
    answerD: "A Leopardess",
    question: "What would you call a female badger?",
  },
  {
    category: "Science",
    correctAnswer: "Rabies",
    answerA: "Rabies",
    answerB: "Meningitis",
    answerC: "Syphilis",
    answerD: "Alzeimer's",
    question: "What Is Hydrophobia Better Known As",
  },
  {
    category: "Science",
    correctAnswer: "A Bull",
    answerA: "A Bull",
    answerB: "A Billy",
    answerC: "A Cob",
    answerD: "A Hob",
    question: "What is the word for a male yak?",
  },
  {
    category: "Science",
    correctAnswer: "study of the mouth and its diseases",
    answerA: "study of the mouth and its diseases",
    answerB: "music in society, usually non-western music",
    answerC: "illness",
    answerD: "embryos",
    question: "What is Stomatology the study of?",
  },
  {
    category: "Science",
    correctAnswer: "Louis Daguerre",
    answerA: "Louis Daguerre",
    answerB: "John Logie Baird",
    answerC: "Thomas Edison",
    answerD: "Emile Berliner",
    question: "Who Took The First Practical Photograph?",
  },
  {
    category: "Music",
    correctAnswer: "The Beatles",
    answerA: "The Beatles",
    answerB: "Deep Purple",
    answerC: "Feeder",
    answerD: "Uriah Heep",
    question: "Which English rock band released the album 'Help!'?",
  },
  {
    category: "Music",
    correctAnswer: "Funkytown",
    answerA: "Funkytown",
    answerB: "Achy Breaky Heart",
    answerC: "Convoy",
    answerD: "Too Shy",
    question: "Lipps, Inc. had a one hit wonder in 1980 with which song?",
  },
  {
    category: "Music",
    correctAnswer: "Devo",
    answerA: "Devo",
    answerB: "MercyMe",
    answerC: "Three 6 Mafia",
    answerD: "The Velvet Underground",
    question:
      'The Lee Dorsey Song "Working In A Coal Mine" Was Later Covered By Which Quirky Band"?',
  },
  {
    category: "Music",
    correctAnswer: "The Beatles",
    answerA: "The Beatles",
    answerB: "Oasis",
    answerC: "Led Zeppelin",
    answerD: "The Clash",
    question: "Which English rock band released the song 'Hey Jude'?",
  },
  {
    category: "Music",
    correctAnswer: "The Police",
    answerA: "The Police",
    answerB: "Level 42",
    answerC: "Wings",
    answerD: "Ultravox",
    question:
      "Which English rock band released the song 'Every Breath You Take'?",
  },
  {
    category: "Music",
    correctAnswer: "Prince",
    answerA: "Prince",
    answerB: "James Brown",
    answerC: "Chris Brown",
    answerD: "Jamiroquai",
    question:
      "With Which Artist Is The Funk Band 'The New Power Generation' Associated?",
  },
  {
    category: "Music",
    correctAnswer: "Smile",
    answerA: "Smile",
    answerB: "Grin",
    answerC: "Laugh",
    answerD: "Cry",
    question: "Which legendary Beach boys album was never completed?",
  },
  {
    category: "Music",
    correctAnswer: "Young MC",
    answerA: "Young MC",
    answerB: "Blind Melon",
    answerC: "The Weather Girls",
    answerD: "Faith No More",
    question: "Who had a hit in 1989 with Bust a Move?",
  },
  {
    category: "Music",
    correctAnswer: "Makin' It",
    answerA: "Makin' It",
    answerB: "Cum on Feel the Noize",
    answerC: "Barbie Girl",
    answerD: "Don't Leave Me This Way",
    question: "David Naughton had a one hit wonder with which song?",
  },
  {
    category: "Music",
    correctAnswer: "Kajagoogoo",
    answerA: "Kajagoogoo",
    answerB: "Norman Greenbaum",
    answerC: "Suzi Quatro",
    answerD: "The Vapors",
    question: "'Too Shy' was a one hit wonder in 1983 by which artist?",
  },
  {
    category: "Music",
    correctAnswer: "Led Zeppelin",
    answerA: "Led Zeppelin",
    answerB: "Cocteau Twins",
    answerC: "Lostprophets",
    answerD: "The Kinks",
    question:
      "Which English rock band released the song 'Good Times Bad Times'?",
  },
  {
    category: "Music",
    correctAnswer: "Coldplay",
    answerA: "Coldplay",
    answerB: "Level 42",
    answerC: "Deep Purple",
    answerD: "Feeder",
    question: "Which British band released the studio album 'Ghost Stories'?",
  },
  {
    category: "Music",
    correctAnswer: "The Jimi Hendrix Experience",
    answerA: "The Jimi Hendrix Experience",
    answerB: "Poison",
    answerC: "The Pussycat Dolls",
    answerD: "Three 6 Mafia",
    question:
      "Which English-American psychedelic rock band released the album 'Electric Ladyland'?",
  },
  {
    category: "Music",
    correctAnswer: "Ring of Fire",
    answerA: "Ring of Fire",
    answerB: "MacArthur Park",
    answerC: "Can't Get Used to Losing You",
    answerD: "Landslide",
    question:
      "Which song, originally recorded by Johnny Cash, was later covered by Wall of Voodoo?",
  },
  {
    category: "Music",
    correctAnswer: "Crash Test Dummies",
    answerA: "Crash Test Dummies",
    answerB: "Cheryl Lynn",
    answerC: "Minnie Riperton",
    answerD: "Buster Poindexter",
    question: "Who had a hit in 1993 with Mmm Mmm Mmm Mmm?",
  },
  {
    category: "Music",
    correctAnswer: "Ha*Ash",
    answerA: "Ha*Ash",
    answerB: "The Pussycat Dolls",
    answerC: "Three 6 Mafia",
    answerD: "The Velvet Underground",
    question: "Which band includes 'Hanna Nicole'?",
  },
  {
    category: "Music",
    correctAnswer: "American Woman",
    answerA: "American Woman",
    answerB: "The Man Who Sold the World",
    answerC: "The Chain",
    answerD: "Where Is My Mind",
    question:
      "Which song was originally recorded by The Guess Who and was later covered by Lenny Kravitz?",
  },
  {
    category: "Music",
    correctAnswer: "The Beach Boys",
    answerA: "The Beach Boys",
    answerB: "The Velvet Underground",
    answerC: "The Monkees",
    answerD: "Fleetwood Mac",
    question:
      "Which American rock band released the song 'Wouldn't It Be Nice'?",
  },
  {
    category: "Music",
    correctAnswer: "Guns N Roses",
    answerA: "Guns N Roses",
    answerB: "Sex Pistols",
    answerC: "The Ramones",
    answerD: "The Clash",
    question: 'With Which Rock Band Does "Slash" Play Guitar?',
  },
  {
    category: "Music",
    correctAnswer: "Eagles",
    answerA: "Eagles",
    answerB: "The Pussycat Dolls",
    answerC: "Three 6 Mafia",
    answerD: "The Velvet Underground",
    question: "Which band includes 'Don Henley'?",
  },
  {
    category: "Music",
    correctAnswer: '"I Will Always Love You" by Whitney Houston',
    answerA: '"I Will Always Love You" by Whitney Houston',
    answerB: '"SpongeBob SquarePants Theme" by Painty the Pirate',
    answerC: `"I'm Real (Murder Remix) by Jennifer Lopez and Ja Rule`,
    answerD: '"Old Man" by Neil Young',
    question:
      'Which song begins with the lyrics: "If I should stay, I would only be in your way."?',
  },
  {
    category: "Music",
    correctAnswer: "Can The Can",
    answerA: "Can The Can",
    answerB: "Do The Do",
    answerC: "See The Sea",
    answerD: "Dance The Dance",
    question: "What Was Suzi Quatro's First Hit In 1973?",
  },
  {
    category: "Music",
    correctAnswer: "Elton John",
    answerA: "Elton John",
    answerB: "Mika",
    answerC: "Madonna",
    answerD: "Eric Clapton",
    question:
      "Which English rock singer-songwriter, composer and pianist released the studio album 'Captain Fantastic and the Brown Dirt Cowboy'?",
  },
  {
    category: "Music",
    correctAnswer: "You Light Up My Life",
    answerA: "You Light Up My Life",
    answerB: "Don't Wanna Fall in Love",
    answerC: "The Hustle",
    answerD: "Cars",
    question: "Debby Boone had a one hit wonder in 1977 with which song?",
  },
  {
    category: "Music",
    correctAnswer: "Simon & Garfunkel",
    answerA: "Simon & Garfunkel",
    answerB: "The Beatles",
    answerC: "The Rolling Stones",
    answerD: "Bob Dylan",
    question: "Who Sang El Condor Pasa (If I Could)",
  },
  {
    category: "Music",
    correctAnswer: "Percussion",
    answerA: "Percussion",
    answerB: "String",
    answerC: "Wind",
    answerD: "Keyboard",
    question: "What type of instrument is a marimba?",
  },
  {
    category: "Music",
    correctAnswer: "Jonas Brothers",
    answerA: "Jonas Brothers",
    answerB: "The Pussycat Dolls",
    answerC: "Three 6 Mafia",
    answerD: "The Velvet Underground",
    question: "Which band includes 'Joe Jonas'?",
  },
  {
    category: "Music",
    correctAnswer: "The Reed",
    answerA: "The Reed",
    answerB: "The Bucket",
    answerC: "The Tap",
    answerD: "The Curl",
    question:
      "What Is The Sound Producing Equipment Element Of Many Woodwind Instrument Called?",
  },
  {
    category: "Music",
    correctAnswer: "Queen",
    answerA: "Queen",
    answerB: "Level 42",
    answerC: "Deep Purple",
    answerD: "Feeder",
    question: "Which British rock band released the song 'Fat Bottomed Girls'?",
  },
  {
    category: "Music",
    correctAnswer: "The Prodigy",
    answerA: "The Prodigy",
    answerB: "Squeeze",
    answerC: "Gorillaz",
    answerD: "Kaiser Chiefs",
    question:
      "Which English electronic dance music group released the song 'Firestarter'?",
  },
  {
    category: "Music",
    correctAnswer: "Wagner",
    answerA: "Wagner",
    answerB: "Hoffman",
    answerC: "Schneider",
    answerD: "Strauss",
    question: "Whose Operas Include Tanhauser & Tristan Und Isolde?",
  },
  {
    category: "Music",
    correctAnswer: "Bee Gees",
    answerA: "Bee Gees",
    answerB: "Level 42",
    answerC: "Culture Club",
    answerD: "Dire Straits",
    question: "Which band includes 'Barry Gibb'?",
  },
  {
    category: "Music",
    correctAnswer: "The Rolling Stones",
    answerA: "The Rolling Stones",
    answerB: "McFly",
    answerC: "Delirious?",
    answerD: "Depeche Mode",
    question:
      "Which English rock band released the studio album 'Let It Bleed'?",
  },
  {
    category: "Music",
    correctAnswer: "Pink Floyd",
    answerA: "Pink Floyd",
    answerB: "Wings",
    answerC: "Rudimental",
    answerD: "The Alan Parsons Project",
    question: "Which band includes 'Nick Mason'?",
  },
  {
    category: "Music",
    correctAnswer: "Girls' Generation",
    answerA: "Girls' Generation",
    answerB: "Big Bang",
    answerC: "BTS",
    answerD: "Apink",
    question: "Which band includes 'Taeyeon'?",
  },
  {
    category: "Music",
    correctAnswer: "Irving Berlin",
    answerA: "Irving Berlin",
    answerB: "Stephen Sondheim",
    answerC: "Andrew Lloyd Webber",
    answerD: "George Gershwin",
    question: `Who Wrote The Musical "There's No Business Like Show Business"?`,
  },
  {
    category: "Music",
    correctAnswer: "It Takes Two",
    answerA: "It Takes Two",
    answerB: "I Touch Myself",
    answerC: "How Bizarre",
    answerD: "Whip It",
    question: "What song did Rob Base & DJ E-Z Rock have a hit with in 1988?",
  },
  {
    category: "Music",
    correctAnswer: "Tchaikovsky",
    answerA: "Tchaikovsky",
    answerB: "Handel",
    answerC: "Bach",
    answerD: "Schuberg",
    question: "Who was the composer of 'The Nutcracker' ballet?",
  },
  {
    category: "Music",
    correctAnswer: "Queen",
    answerA: "Queen",
    answerB: "Level 42",
    answerC: "Deep Purple",
    answerD: "Feeder",
    question: "Which band includes 'Roger Taylor'?",
  },
  {
    category: "Music",
    correctAnswer: "The White Stripes",
    answerA: "The White Stripes",
    answerB: "The Pussycat Dolls",
    answerC: "Three 6 Mafia",
    answerD: "The Velvet Underground",
    question: "Which band includes 'Jack White'?",
  },
  {
    category: "Music",
    correctAnswer: "Rihanna",
    answerA: "Rihanna",
    answerB: "Drake",
    answerC: "Nicki Minaj",
    answerD: "Ricky Martin",
    question: "Which singer released the studio album 'Anti'?",
  },
  {
    category: "Music",
    correctAnswer: "Daft Punk",
    answerA: "Daft Punk",
    answerB: "Gong",
    answerC: "Indochine",
    answerD: "Nouvelle Vague",
    question: "Which French electronica duo released the song 'One More Time'?",
  },
  {
    category: "Music",
    correctAnswer: "The Stranglers",
    answerA: "The Stranglers",
    answerB: "Sex Pistols",
    answerC: "Violent Femmes",
    answerD: "T. Rex",
    question: "Who sang 'No More Heroes'?",
  },
  {
    category: "Music",
    correctAnswer: "Take That",
    answerA: "Take That",
    answerB: "Talk Talk",
    answerC: "Feeder",
    answerD: "Bring Me the Horizon",
    question: "Which band includes 'Robbie Williams'?",
  },
  {
    category: "Music",
    correctAnswer: "Nirvana",
    answerA: "Nirvana",
    answerB: "The Velvet Underground",
    answerC: "Pearl Jam",
    answerD: "Metallica",
    question:
      "Which American rock band released the song 'Smells Like Teen Spirit'?",
  },
  {
    category: "Music",
    correctAnswer: "Woodwind",
    answerA: "Woodwind",
    answerB: "Brass",
    answerC: "Percussion",
    answerD: "Stringed",
    question: "What type of instrument is a fife?",
  },
  {
    category: "Music",
    correctAnswer: "Spice Girls",
    answerA: "Spice Girls",
    answerB: "Editors",
    answerC: "Cradle of Filth",
    answerD: "The Sweet",
    question: "Which band includes 'Emma Bunton'?",
  },
  {
    category: "Music",
    correctAnswer: "Pop Muzik",
    answerA: "Pop Muzik",
    answerB: "No Rain",
    answerC: "I'm Too Sexy",
    answerD: "How Do You Talk to an Angel?",
    question: "What song did M have a hit with in 1979?",
  },
  {
    category: "Music",
    correctAnswer: "Sonic Youth",
    answerA: "Sonic Youth",
    answerB: "The Pussycat Dolls",
    answerC: "Three 6 Mafia",
    answerD: "The Velvet Underground",
    question: "Which band includes 'Jim O'Rourke'?",
  },
  {
    category: "Music",
    correctAnswer: "AC/DC",
    answerA: "AC/DC",
    answerB: "Pendulum",
    answerC: "INXS",
    answerD: "Savage Garden",
    question:
      "Which Australian hard rock band released the studio album 'Back in Black'?",
  },
  {
    category: "Film & TV",
    correctAnswer:
      "A slacker seeks restitution for a rug ruined by debt collectors.",
    answerA: "A slacker seeks restitution for a rug ruined by debt collectors.",
    answerB:
      "On a journey to find the cure for a curse, a boy finds himself in the middle of a war.",
    answerC:
      "After awakening from a coma, a former assassin wreaks vengeance on those who betrayed her.",
    answerD:
      "The son of a former boxer is trained by his father for a mixed martial arts tournament.",
    question: "What is the plot of the movie The Big Lebowski?",
  },
  {
    category: "Film & TV",
    correctAnswer:
      "An examination of the ways in which war impacts the lives of several friends.",
    answerA:
      "An examination of the ways in which war impacts the lives of several friends.",
    answerB:
      "An NYPD officer tries to save his wife taken hostage by terrorists during a Christmas party.",
    answerC:
      "A freed slave sets out to rescue his wife from a brutal plantation-owner.",
    answerD: "A janitor has a gift for mathematics.",
    question: "What is the plot of the movie The Deer Hunter?",
  },
  {
    category: "Film & TV",
    correctAnswer: `"I'm walking here! I'm walking here!"`,
    answerA: `"I'm walking here! I'm walking here!"`,
    answerB: '"I feel the need - the need for speed!"',
    answerC: '"Shane. Shane. Come back!"',
    answerD: '"Attica! Attica!"',
    question: "Which of these quotes is from the film 'Midnight Cowboy'?",
  },
  {
    category: "Film & TV",
    correctAnswer: "On Her Majesty's Secret Service",
    answerA: "On Her Majesty's Secret Service",
    answerB: "Live and Let Die",
    answerC: "Goldeneye",
    answerD: "Dr. No",
    question: "Which James Bond Movie Is Set During The Christmas Period?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Jennifer Connelly",
    answerA: "Jennifer Connelly",
    answerB: "Helen Mirren",
    answerC: "Maggie Smith",
    answerD: "Marisa Tomei",
    question:
      "Who won the 2001 Academy Award for Best Supporting Actress for playing the role of Alicia Nash in A Beautiful Mind?",
  },
  {
    category: "Film & TV",
    correctAnswer:
      "A family heads to a hotel for the winter where a presence influences the father into violence.",
    answerA:
      "A family heads to a hotel for the winter where a presence influences the father into violence.",
    answerB:
      "A group of low-level criminals fight to track down a priceless stolen diamond.",
    answerC:
      "After the death of a tycoon, reporters scramble to uncover the meaning of his final utterance.",
    answerD:
      "A car designer and driver battle to build a revolutionary race car.",
    question: "What is the plot of the movie The Shining?",
  },
  {
    category: "Film & TV",
    correctAnswer: '"Nobody makes me bleed my own blood. Nobody!"',
    answerA: '"Nobody makes me bleed my own blood. Nobody!"',
    answerB: '"Are you not entertained?"',
    answerC:
      '"I have had it with these mother—— snakes on this mother—— plane!"',
    answerD:
      '"What is this? A center for ants? How can we be expected to teach children to learn how to read…if they can’t even fit inside the building?"',
    question:
      "Which of these quotes is from the film 'Dodgeball: A True Underdog Story'?",
  },
  {
    category: "Film & TV",
    correctAnswer: '"I love the smell of napalm in the morning."',
    answerA: '"I love the smell of napalm in the morning."',
    answerB: `"We'll always have Paris."`,
    answerC: '"Yo, Adrian!"',
    answerD: `"Frankly, my dear, I don't give a damn."`,
    question: "Which of these quotes is from the film 'Apocalypse Now'?",
  },
  {
    category: "Film & TV",
    correctAnswer: "M",
    answerA: "M",
    answerB: "Austin Powers: International Man of Mystery",
    answerC: "Apocalypse Now",
    answerD: "Home Alone",
    question: "Which film contains the character 'Hans Beckert'?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Cate Blanchett",
    answerA: "Cate Blanchett",
    answerB: "Laura Linney",
    answerC: "Virginia Madsen",
    answerD: "Sophie Okonedo",
    question:
      "Who won the 2004 Academy Award for Best Supporting Actress for playing the role of Katharine Hepburn in The Aviator?",
  },
  {
    category: "Film & TV",
    correctAnswer: '"La-dee-da, la-dee-da."',
    answerA: '"La-dee-da, la-dee-da."',
    answerB: `"Who's on first."`,
    answerC: `"I'm gonna make him an offer he can't refuse."`,
    answerD:
      '"I’m already pregnant. So, what other shenanigans could I get myself into?"',
    question: "Which of these quotes is from the film 'Annie Hall'?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Million Dollar Baby",
    answerA: "Million Dollar Baby",
    answerB: "The Aviator",
    answerC: "Finding Neverland",
    answerD: "Ray",
    question: "Which film won the Academy Award for Best Picture in 2004?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Brad Pitt",
    answerA: "Brad Pitt",
    answerB: "Nicholas Cage",
    answerC: "John Travolta",
    answerD: "Edward Norton",
    question:
      "In The Movie 'Interview With The Vampire' Who Played The Vampire Being Interviewed?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Madonna",
    answerA: "Madonna",
    answerB: "Shirley Bassey",
    answerC: "Sheena Easton",
    answerD: "Sheryl Crow",
    question:
      "Who performed the theme song to the James Bond film Die Another Day?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Kaa",
    answerA: "Kaa",
    answerB: "Baloo",
    answerC: "Shere Khan",
    answerD: "King Louie",
    question:
      "What is the name of the snake in the Disney film The Jungle Book?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Gladiator",
    answerA: "Gladiator",
    answerB: "Chocolat",
    answerC: "Crouching Tiger, Hidden Dragon",
    answerD: "Erin Brockovich",
    question: "Which film won the Academy Award for Best Picture in 2000?",
  },
  {
    category: "Film & TV",
    correctAnswer: "1980",
    answerA: "1980",
    answerB: "1975",
    answerC: "1985",
    answerD: "1990",
    question: "In which year was The Shining first released in the cinema?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Crash",
    answerA: "Crash",
    answerB: "Brokeback Mountain",
    answerC: "Capote",
    answerD: "Good Night, and Good Luck.",
    question: "Which film won the Academy Award for Best Picture in 2005?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Tim Curry",
    answerA: "Tim Curry",
    answerB: "Aaron Paul",
    answerC: "Mark Hamill",
    answerD: "Richard Burton",
    question:
      "Which actor has played roles in films including The Rocky Horror Picture Show and The Hunt for Red October?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Duran Duran",
    answerA: "Duran Duran",
    answerB: "Garbage",
    answerC: "Chris Cornell",
    answerD: "Lulu",
    question:
      "Who performed the theme song to the James Bond film A View to a Kill?",
  },
  {
    category: "Film & TV",
    correctAnswer: '"Open the pod bay doors, please, HAL."',
    answerA: '"Open the pod bay doors, please, HAL."',
    answerB: `"Forget it, Jake, it's Chinatown."`,
    answerC: '"I love lamp."',
    answerD: '"I’m the guy who does his job. You must be the other guy."',
    question: "Which of these quotes is from the film '2001: A Space Odyssey'?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Spilled champagne",
    answerA: "Spilled champagne",
    answerB: "A lightning strike",
    answerC: "Divine intervention",
    answerD: "A plutonium power core",
    question: "What caused the computer in Electric Dreams to become alive?",
  },
  {
    category: "Film & TV",
    correctAnswer: "The Sting",
    answerA: "The Sting",
    answerB: "American Graffiti",
    answerC: "Cries and Whispers",
    answerD: "The Exorcist",
    question: "Which film won the Academy Award for Best Picture in 1973?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Scooby Doo",
    answerA: "Scooby Doo",
    answerB: "Spongebob Squarepants",
    answerC: "Teenage Mutant Ninja Turtles",
    answerD: "South Park",
    question: "In Which Cartoon Might You Encounter 'The Mystery Machine'?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Marlon Brando",
    answerA: "Marlon Brando",
    answerB: "Robert Shaw",
    answerC: "Glenn Close",
    answerD: "Samuel L. Jackson",
    question: "Which actor played the role of Vito Corleone in The Godfather?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Around the World in 80 Days",
    answerA: "Around the World in 80 Days",
    answerB: "Friendly Persuasion",
    answerC: "Giant",
    answerD: "The King and I",
    question: "Which film won the Academy Award for Best Picture in 1956?",
  },
  {
    category: "Film & TV",
    correctAnswer: '"I have always depended on the kindness of strangers."',
    answerA: '"I have always depended on the kindness of strangers."',
    answerB: `"A boy's best friend is his mother."`,
    answerC: '"Oh what a day. What a lovely day!"',
    answerD: `"Wait a minute, wait a minute. You ain't heard nothin' yet!"`,
    question:
      "Which of these quotes is from the film 'A Streetcar Named Desire'?",
  },
  {
    category: "Film & TV",
    correctAnswer: "2001",
    answerA: "2001",
    answerB: "1992",
    answerC: "1995",
    answerD: "1998",
    question:
      "In which year was The Lord of the Rings: The Fellowship of the Ring first released in the cinema?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Jim Carrey",
    answerA: "Jim Carrey",
    answerB: "Gerard Butler",
    answerC: "Hugh Jackman",
    answerD: "Michael Fassbender",
    question:
      "Which actor has played roles in films including Batman Forever and The Mask?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Chevy Chase",
    answerA: "Chevy Chase",
    answerB: "Steve Martin",
    answerC: "Tim Allen",
    answerD: "Tom Hanks",
    question:
      "Who plays the lead role of the accident prone Clark Griswold in the 1989 'National Lampoon's Christmas Vacation''?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Indiana Jones and the Last Crusade",
    answerA: "Indiana Jones and the Last Crusade",
    answerB: "The Godfather",
    answerC: "Spotlight",
    answerD: "The Green Mile",
    question:
      "Name the movie that matches the following plot summary: 'After his father goes missing, a professor finds himself in a search for the Holy Grail.'",
  },
  {
    category: "Film & TV",
    correctAnswer: "Pennsylvania",
    answerA: "Pennsylvania",
    answerB: "Ohio",
    answerC: "Maryland",
    answerD: "Delaware",
    question:
      "In which American state is George A. Romero's 1968 film 'Night Of The Living Dead' set?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Naomi Watts",
    answerA: "Naomi Watts",
    answerB: "Melissa Leo",
    answerC: "Frances Conroy",
    answerD: "Laura Linney",
    question:
      "Which actor has featued in films including Birdman and Twin Peaks?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Jonah Hill",
    answerA: "Jonah Hill",
    answerB: "Javier Bardem",
    answerC: "Hugo Weaving",
    answerD: "Warwick Davis",
    question:
      "Which actor has featured in films including The Wolf of Wall Street and Moneyball?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Louis Gossett, Jr.",
    answerA: "Louis Gossett, Jr.",
    answerB: "Charles Durning",
    answerC: "John Lithgow",
    answerD: "James Mason",
    question:
      "Who won the 1982 Academy Award for Best Supporting Actor for playing the role of Sgt. Emil Foley in An Officer and a Gentleman?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Pierce Brosnan",
    answerA: "Pierce Brosnan",
    answerB: "George Lazenby",
    answerC: "Timothy Dalton",
    answerD: "Sean Connery",
    question: "Who played the role of James Bond in Tomorrow Never Dies?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Green Book",
    answerA: "Green Book",
    answerB: "Platoon",
    answerC: "V for Vendetta",
    answerD: "The Dark Knight",
    question:
      "Name the movie that matches the following plot summary: 'A working-class bouncer becomes the driver of an African-American classical pianist.'",
  },
  {
    category: "Film & TV",
    correctAnswer: "Being There",
    answerA: "Being There",
    answerB: "The Godfather",
    answerC: "Pirates of the Caribbean",
    answerD: "Wall Street",
    question: "Which film contains the character 'Chance the Gardener'?",
  },
  {
    category: "Film & TV",
    correctAnswer: '"I’m just one stomach flu away from my goal weight."',
    answerA: '"I’m just one stomach flu away from my goal weight."',
    answerB: `"I'll be back."`,
    answerC: `"Tell 'em to go out there with all they got and win just one for the Gipper."`,
    answerD: `"I'm the king of the world!"`,
    question: "Which of these quotes is from the film 'The Devil Wears Prada'?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Stromboli",
    answerA: "Stromboli",
    answerB: "The Evil Queen",
    answerC: "Ursula",
    answerD: "Maleficent",
    question: "What is the name of the villain in Pinocchio?",
  },
  {
    category: "Film & TV",
    correctAnswer: "George Lazenby",
    answerA: "George Lazenby",
    answerB: "Roger Moore",
    answerC: "Pierce Brosnan",
    answerD: "Sean Connery",
    question:
      "Who played the role of James Bond in On Her Majesty's Secret Service?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Sean Penn",
    answerA: "Sean Penn",
    answerB: "Richard Jenkins",
    answerC: "Frank Langella",
    answerD: "Brad Pitt",
    question:
      "Who won the 2008 Academy Award for Best Leading Actor for playing the role of Harvey Milk in Milk?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Parasite",
    answerA: "Parasite",
    answerB: "Vertigo",
    answerC: "The Big Lebowski",
    answerD: "Casino",
    question:
      "Name the movie that matches the following plot summary: 'A destitute family builds a symbiotic relationship with a wealthy family.'",
  },
  {
    category: "Film & TV",
    correctAnswer: "David Yates",
    answerA: "David Yates",
    answerB: "Steven Spielberg",
    answerC: "Woody Allen",
    answerD: "Martin Scorsese",
    question:
      "Which director directed Harry Potter and the Order of the Phoenix?",
  },
  {
    category: "Film & TV",
    correctAnswer: "No Country for Old Men",
    answerA: "No Country for Old Men",
    answerB: "Hacksaw Ridge",
    answerC: "Pulp Fiction",
    answerD: "Aliens",
    question:
      "Name the movie that matches the following plot summary: 'Violence and mayhem ensue after a man stumbles upon more than two million dollars.'",
  },
  {
    category: "Film & TV",
    correctAnswer: "Mickey Rooney",
    answerA: "Mickey Rooney",
    answerB: "Stephen Fry",
    answerC: "Michael Ironside",
    answerD: "Luke Evans",
    question:
      "Which actor has featued in films including Phantom of the Megaplex and Breakfast at Tiffany's?",
  },
  {
    category: "Film & TV",
    correctAnswer: "Braveheart",
    answerA: "Braveheart",
    answerB: "Trainspotting",
    answerC: "My Neighbour Totoro",
    answerD: "Apocalypse Now",
    question:
      "Name the movie that matches the following plot summary: 'A Scottish warrior leads his countrymen in a rebellion to free his homeland.'",
  },
  {
    category: "Film & TV",
    correctAnswer: "Coco",
    answerA: "Coco",
    answerB: "Gone Girl",
    answerC: "The Usual Suspects",
    answerD: "Aliens",
    question:
      "Name the movie that matches the following plot summary: 'An aspiring musician enters the Land of the Dead to find his great-great-grandfather, a legendary singer.'",
  },
  {
    category: "Film & TV",
    correctAnswer: "City of God",
    answerA: "City of God",
    answerB: "Die Hard",
    answerC: "Unforgiven",
    answerD: "A Beautiful Mind",
    question:
      "Name the movie that matches the following plot summary: 'In the slums of Rio, two kids' paths diverge as one becomes a photographer and the other a kingpin.'",
  },
  {
    category: "Film & TV",
    correctAnswer:
      "After a prince is betrayed and enslaved, he regains his freedom and comes back for revenge.",
    answerA:
      "After a prince is betrayed and enslaved, he regains his freedom and comes back for revenge.",
    answerB:
      "A group of thieves feel the pressure from the police when they leave a clue at their latest heist.",
    answerC:
      "A car salesman's inept crime falls apart due to his and his henchmen's bungling.",
    answerD:
      "After his father goes missing, a professor finds himself in a search for the Holy Grail.",
    question: "What is the plot of the movie Ben-Hur?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Canelazo",
    answerA: "Canelazo",
    answerB: "Kumis",
    answerC: "Rakı",
    answerD: "Tuba",
    question: "Which of these drinks would you associate with Equador?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Sweden ",
    answerA: "Sweden ",
    answerB: "Denmark",
    answerC: "Finland",
    answerD: "Norway",
    question: "Which country does one associate with 'Lussekatter'?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Puerto Rico",
    answerA: "Puerto Rico",
    answerB: "Portugal",
    answerC: "Peru",
    answerD: "Latvia",
    question: "In which country is pitorro a popular drink?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Cannelloni",
    answerA: "Cannelloni",
    answerB: "Garganelli",
    answerC: "Bavette",
    answerD: "Ziti",
    question: "Which pasta's name means 'Large reeds'?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Whelk ",
    answerA: "Whelk ",
    answerB: "Escargot",
    answerC: "Mussel",
    answerD: "Conch",
    question: "The Marine Snail Is Better Known As What",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Penne",
    answerA: "Penne",
    answerB: "Ravioli",
    answerC: "Fusilli",
    answerD: "Orecchiette",
    question: "Which pasta's name means 'Pens'?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Taco",
    answerA: "Taco",
    answerB: "Sushi",
    answerC: "Ramen",
    answerD: "Pho",
    question: "Which of these is a popular dish in Mexico?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Veal ",
    answerA: "Veal ",
    answerB: "Beef",
    answerC: "Pork",
    answerD: "Lamb",
    question: "What type of meat is used in the preparation of Osso Bucco?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Pina Colada",
    answerA: "Pina Colada",
    answerB: "Martini",
    answerC: "Negroni",
    answerD: "Daiquiri",
    question: "Which Cocktail contains rum, pineapple and coconut?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Verivorst",
    answerA: "Verivorst",
    answerB: "Cou Cou and Flying Fish",
    answerC: "Plov",
    answerD: "Pad Thai",
    question: "Which of these dishes would you most expect to find in Estonia?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Mama Juana",
    answerA: "Mama Juana",
    answerB: "Gin",
    answerC: "Maotai",
    answerD: "Chibuku",
    question: "Which of these is a popular drink in The Dominican Republic?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Spiciness",
    answerA: "Spiciness",
    answerB: "Calories",
    answerC: "Dairy Content",
    answerD: "Alcohol Content",
    question: "What Does The Scoville Scale Measure?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "St. Louis",
    answerA: "St. Louis",
    answerB: "Munich",
    answerC: "Prague",
    answerD: "New Orleans",
    question: " Where was Budweiser first brewed?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Parma ",
    answerA: "Parma ",
    answerB: "Genoa",
    answerC: "Venice",
    answerD: "Florence",
    question: "Which Italian city gave its name to a cheese and a type of ham?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Peru",
    answerA: "Peru",
    answerB: "Belgium",
    answerC: "Japan",
    answerD: "Cambodia",
    question: "Where in the world would you most expect to be served Ceviche?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Nectarine ",
    answerA: "Nectarine ",
    answerB: "Agave",
    answerC: "Guava",
    answerD: "Lychee",
    question: "Which fruit is a cross between a peach and a plum?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Raw",
    answerA: "Raw",
    answerB: "Fried",
    answerC: "Boiled",
    answerD: "Grilled",
    question: "How is steak tartare cooked?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Almond",
    answerA: "Almond",
    answerB: "Hazelnut",
    answerC: "Brazil Nut",
    answerD: "Walnut",
    question: "What nut is used to make marzipan?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Lamb ",
    answerA: "Lamb ",
    answerB: "Beef",
    answerC: "Pork",
    answerD: "Chicken",
    question: "Traditionally what type of meat is used to make a mousakka?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Pomegranate ",
    answerA: "Pomegranate ",
    answerB: "Mango",
    answerC: "Cranberry",
    answerD: "Raspberry",
    question: "From Which Fruit Is Grenadine Obtained?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "California ",
    answerA: "California ",
    answerB: "Florida",
    answerC: "Texas",
    answerD: "Kansas",
    question: "Which US state exports the most wine?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Sang Som Rum",
    answerA: "Sang Som Rum",
    answerB: "Pitorro",
    answerC: "Tuba",
    answerD: "Port wine",
    question: "Which of these drinks would you associate with Thailand?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Twins",
    answerA: "Twins",
    answerB: "Squid-like",
    answerC: "Pens",
    answerD: "Bibs",
    question: "The pasta gemelli has what meaning in Italian?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "The Netherlands ",
    answerA: "The Netherlands ",
    answerB: "Germany",
    answerC: "France",
    answerD: "Scotland",
    question: "From which country does Edam cheese originate?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Beetles ",
    answerA: "Beetles ",
    answerB: "Raspberries",
    answerC: "Blood",
    answerD: "Rust",
    question: "From what is the red  dye carmine derived?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Pomegranate ",
    answerA: "Pomegranate ",
    answerB: "Mango",
    answerC: "Cranberry",
    answerD: "Raspberry",
    question: "From Which Fruit Is Grenadine Made?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Screwdriver ",
    answerA: "Screwdriver ",
    answerB: "Hammer",
    answerC: "Spanner",
    answerD: "Wrench",
    question: "Which cocktail shares its name with a tool?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Burrito ",
    answerA: "Burrito ",
    answerB: "Taco",
    answerC: "Fajita",
    answerD: "Quesadilla",
    question: "Which Mexican Dish Translates Into English As Little Donkey?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Khao Soi",
    answerA: "Khao Soi",
    answerB: "Toad in the Hole",
    answerC: "Kentucky Fried Chicken",
    answerD: "Chicken Tikka Masala",
    question:
      "Which of these dishes is most commonly found in Northern regions of Thailand?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Vodka ",
    answerA: "Vodka ",
    answerB: "Whiskey",
    answerC: "Gin",
    answerD: "Martini",
    question:
      "A black Russian cocktail is made with one part coffee liqueur and two parts of which spirit?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Tomato ",
    answerA: "Tomato ",
    answerB: "Onion",
    answerC: "Garlic",
    answerD: "Mango",
    question: "'love apple' is a nickname for which food?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Feijoada",
    answerA: "Feijoada",
    answerB: "Poutine",
    answerC: "Couscous",
    answerD: "Ambuyat",
    question: "Which of these dishes is most associated with Brazil?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Tayberry",
    answerA: "Tayberry",
    answerB: "Rackberry",
    answerC: "Basberry",
    answerD: "Marberry",
    question: "What is a cross between a blackberry and a raspberry?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Herring ",
    answerA: "Herring ",
    answerB: "Salmon",
    answerC: "Tuna",
    answerD: "Mackerel",
    question: "What sort of fish is a kipper?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Mexico ",
    answerA: "Mexico ",
    answerB: "USA",
    answerC: "Guatemala",
    answerD: "Costa Rica",
    question: "From which country does Tabasco sauce originate?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Potato dumplings",
    answerA: "Potato dumplings",
    answerB: "Raw beef",
    answerC: "Pickled turnip",
    answerD: "Carrot sauce",
    question: "What is gnocchi?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Bergamot ",
    answerA: "Bergamot ",
    answerB: "Lemon",
    answerC: "Grapefruit",
    answerD: "Lime",
    question:
      "Which citrus fruit grows predominantly in Italy and is used in Earl Grey tea and eau de Cologne?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Melon",
    answerA: "Melon",
    answerB: "Grape",
    answerC: "Apple",
    answerD: "Orange",
    question: "What Fruit Is A Cantaloupe?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Cannoli",
    answerA: "Cannoli",
    answerB: "Bomboloni",
    answerC: "Kringle",
    answerD: "Torti",
    question:
      "What is the name of an Italian pastry made of deep-fried dough shaped into a tube and filled with custard or cream?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Ice cream ",
    answerA: "Ice cream ",
    answerB: "Custard",
    answerC: "Chocolate",
    answerD: "Consommé",
    question:
      "Baked Alaska has meringue on the outside , what does the meringue cover?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Butter ",
    answerA: "Butter ",
    answerB: "Cheese",
    answerC: "Milk",
    answerD: "Cream",
    question:
      "Along with wine vinegar and egg yolk, what other ingredient would you find in hollandaise sauce?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Mayans ",
    answerA: "Mayans ",
    answerB: "Greeks",
    answerC: "Aztecs",
    answerD: "Babylonians",
    question:
      "Which Ancient Civilisation Were Drinking Chocolate Milk As Long Ago As 600 BC?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Goulash",
    answerA: "Goulash",
    answerB: "Haggis",
    answerC: "Aloco",
    answerD: "Succotash",
    question: "Which of these dishes is most associated with Hungary?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Orange",
    answerA: "Orange",
    answerB: "Strawberry",
    answerC: "Apple",
    answerD: "Blueberry",
    question: "Which of these fruits is a citrus fruit?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Dutch ",
    answerA: "Dutch ",
    answerB: "German",
    answerC: "Danish",
    answerD: "French",
    question: "What nationality is the lager producer, `grolsch'?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Bread ",
    answerA: "Bread ",
    answerB: "Cheese",
    answerC: "Fish",
    answerD: "Mushroom",
    question: "What type of food is a bloomer?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Ribbon pasta",
    answerA: "Ribbon pasta",
    answerB: "Soup pasta",
    answerC: "Strand pasta",
    answerD: "Tubular pasta",
    question: "What type of pasta is lasagne?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Europe",
    answerA: "Europe",
    answerB: "Central America",
    answerC: "Central Asia",
    answerD: "China",
    question: "Where in the world are turnips originally from?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Bread ",
    answerA: "Bread ",
    answerB: "Cheese",
    answerC: "Cake",
    answerD: "Wine",
    question: "Bruschetta is what?",
  },
  {
    category: "Food & Drink",
    correctAnswer: "Mushrooms ",
    answerA: "Mushrooms ",
    answerB: "Garlic",
    answerC: "Onion",
    answerD: "Cabbage",
    question: "Which Vegetable Can Be Oyster, Chestnut, or Shitaki?",
  },
  {
    category: "Geography",
    correctAnswer: "Europe",
    answerA: "Europe",
    answerB: "South America",
    answerC: "Oceania",
    answerD: "Asia",
    question: "The country of Andorra is on which continent?",
  },
  {
    category: "Geography",
    correctAnswer: "White",
    answerA: "White",
    answerB: "Gold",
    answerC: "Green",
    answerD: "Black",
    question: "Which of these colors is included on the flag of Poland?",
  },
  {
    category: "Geography",
    correctAnswer: "Costa Rica",
    answerA: "Costa Rica",
    answerB: "Montenegro",
    answerC: "Andorra",
    answerD: "Grenada",
    question: "San Jose is the capital city of which country?",
  },
  {
    category: "Geography",
    correctAnswer: "Egypt",
    answerA: "Egypt",
    answerB: "Kuwait",
    answerC: "Taiwan",
    answerD: "Spain",
    question: "Cairo is the capital city of which country?",
  },
  {
    category: "Geography",
    correctAnswer: "Turkey",
    answerA: "Turkey",
    answerB: "Egypt",
    answerC: "Jordan",
    answerD: "Israel",
    question: "In which country is the city of Izmir?",
  },
  {
    category: "Geography",
    correctAnswer: "Venezuela",
    answerA: "Venezuela",
    answerB: "Vietnam",
    answerC: "Montenegro",
    answerD: "Vanuatu",
    question:
      "Which region of the world uses '.ve' at the end of its web addresses?",
  },
  {
    category: "Geography",
    correctAnswer: "Medellin",
    answerA: "Medellin",
    answerB: "Buenos Aires",
    answerC: "Salvador",
    answerD: "Valparaíso",
    question: "Which of these cities is in Colombia?",
  },
  {
    category: "Geography",
    correctAnswer: "Ecuador ",
    answerA: "Ecuador ",
    answerB: "Latvia",
    answerC: "Liberia",
    answerD: "Indonesia",
    question: "Which country has taken its name from a line of latitude?",
  },
  {
    category: "Geography",
    correctAnswer: "Russia",
    answerA: "Russia",
    answerB: "Japan",
    answerC: "Mongolia",
    answerD: "Philippines",
    question: "Which of these countries borders North Korea?",
  },
  {
    category: "Geography",
    correctAnswer: "Red with a black two headed eagle in the center.",
    answerA: "Red with a black two headed eagle in the center.",
    answerB: "Three equal vertical bands of green, yellow, and red.",
    answerC: "Black and green triangles divided by a yellow cross.",
    answerD: "Red with a white cross that extends to the edges.",
    question: "What does the flag of Albania look like?",
  },
  {
    category: "Geography",
    correctAnswer: "Honduras",
    answerA: "Honduras",
    answerB: "Laos",
    answerC: "Tanzania",
    answerD: "Brunei",
    question: "Tegucigalpa is the capital city of which country?",
  },
  {
    category: "Geography",
    correctAnswer: "Gambia",
    answerA: "Gambia",
    answerB: "Palau",
    answerC: "South Korea",
    answerD: "Oman",
    question: "Banjul is the capital city of which country?",
  },
  {
    category: "Geography",
    correctAnswer: "Red",
    answerA: "Red",
    answerB: "Orange",
    answerC: "Blue",
    answerD: "White",
    question: "Which of these colors is included on the flag of Belgium?",
  },
  {
    category: "Geography",
    correctAnswer: "Oceania",
    answerA: "Oceania",
    answerB: "South America",
    answerC: "Europe",
    answerD: "Asia",
    question:
      "The country of Federated States of Micronesia is on which continent?",
  },
  {
    category: "Geography",
    correctAnswer: "Atlantic ",
    answerA: "Atlantic ",
    answerB: "Pacific",
    answerC: "Indian",
    answerD: "Arctic",
    question: "In Which Ocean Is The Gulf Stream",
  },
  {
    category: "Geography",
    correctAnswer: "Africa",
    answerA: "Africa",
    answerB: "South America",
    answerC: "Oceania",
    answerD: "Europe",
    question: "The country of Comoros is on which continent?",
  },
  {
    category: "Geography",
    correctAnswer: "Turkey",
    answerA: "Turkey",
    answerB: "Bosnia & Herzegovina",
    answerC: "France",
    answerD: "Italy",
    question:
      "In which country would you find the ancient Greek city of Hierapolis?",
  },
  {
    category: "Geography",
    correctAnswer: "Porto-Novo",
    answerA: "Porto-Novo",
    answerB: "Ashgabat",
    answerC: "Amman",
    answerD: "Lusaka",
    question: "What is the capital city of Benin?",
  },
  {
    category: "Geography",
    correctAnswer: "Prague",
    answerA: "Prague",
    answerB: "Manama",
    answerC: "Berlin",
    answerD: "Valletta",
    question: "What is the capital city of Czechia?",
  },
  {
    category: "Geography",
    correctAnswer: "Tonga",
    answerA: "Tonga",
    answerB: "Samoa",
    answerC: "Mexico",
    answerD: "New Zealand",
    question:
      "Which country altered its timezone in order to be the first to see in the year 2000 ?",
  },
  {
    category: "Geography",
    correctAnswer: "Chile",
    answerA: "Chile",
    answerB: "Scotland",
    answerC: "Tanzania",
    answerD: "USA",
    question: "The territory of Easter Island belongs to which country?",
  },
  {
    category: "Geography",
    correctAnswer: "Jewellers",
    answerA: "Jewellers",
    answerB: "Butchers",
    answerC: "Shoes",
    answerD: "Wine",
    question:
      "What Type Of Shop Predominates On The Ponte Vecchio In Florence?",
  },
  {
    category: "Geography",
    correctAnswer: "Kyiv",
    answerA: "Kyiv",
    answerB: "Sofia",
    answerC: "Belgrade",
    answerD: "Kharkiv",
    question: "What is the capital city of Ukraine?",
  },
  {
    category: "Geography",
    correctAnswer: "Belgium",
    answerA: "Belgium",
    answerB: "Liechtenstein",
    answerC: "Slovenia",
    answerD: "San Marino",
    question: "Which of these countries borders Germany?",
  },
  {
    category: "Geography",
    correctAnswer: "Estonia",
    answerA: "Estonia",
    answerB: "Georgia",
    answerC: "Belarus",
    answerD: "Canada",
    question: "Which of these countries has black on its flag?",
  },
  {
    category: "Geography",
    correctAnswer: "Pakistan",
    answerA: "Pakistan",
    answerB: "Kosovo",
    answerC: "Saudi Arabia",
    answerD: "Ghana",
    question: "Islamabad is the capital city of which country?",
  },
  {
    category: "Geography",
    correctAnswer: "Beijing",
    answerA: "Beijing",
    answerB: "Hong Kong",
    answerC: "Shanghai",
    answerD: "Guangzhou",
    question: "What Is The Capital Of China?",
  },
  {
    category: "Geography",
    correctAnswer: "Egypt",
    answerA: "Egypt",
    answerB: "Qatar",
    answerC: "Lebanon",
    answerD: "Saudi Arabia",
    question: "In which country is the city of Alexandria?",
  },
  {
    category: "Geography",
    correctAnswer: "Oakland",
    answerA: "Oakland",
    answerB: "Sacramento",
    answerC: "New York",
    answerD: "Las Vegas",
    question: "Which city is on the east side of San Francisco Bay?",
  },
  {
    category: "Geography",
    correctAnswer: "Africa",
    answerA: "Africa",
    answerB: "Asia",
    answerC: "North America",
    answerD: "Oceania",
    question: "Where is the world's largest desert?",
  },
  {
    category: "Geography",
    correctAnswer: "Malaysia",
    answerA: "Malaysia",
    answerB: "Philippines",
    answerC: "Vietnam",
    answerD: "Singapore",
    question: "Where would you find the city of Petaling Jaya?",
  },
  {
    category: "Geography",
    correctAnswer: "Pristina",
    answerA: "Pristina",
    answerB: "Lomé",
    answerC: "Monrovia",
    answerD: "Zagreb",
    question: "What is the capital city of Kosovo?",
  },
  {
    category: "Geography",
    correctAnswer: "Sri Lanka",
    answerA: "Sri Lanka",
    answerB: "Indonesia",
    answerC: "Vietnam",
    answerD: "Cambodia",
    question: "Colombo is a city in which country?",
  },
  {
    category: "Geography",
    correctAnswer: "Syria",
    answerA: "Syria",
    answerB: "Thailand",
    answerC: "North Korea",
    answerD: "Puerto Rico",
    question:
      "Which country's flag fits the description of 'Three equal horizontal bands of red white and black. The white band contains two green stars.'?",
  },
  {
    category: "Geography",
    correctAnswer: "Belarus",
    answerA: "Belarus",
    answerB: "Kyrgyzstan",
    answerC: "Tajikistan",
    answerD: "Uzbekistan",
    question: "Which of these countries borders Russia?",
  },
  {
    category: "Geography",
    correctAnswer: "Belgium",
    answerA: "Belgium",
    answerB: "Italy",
    answerC: "Bosnia & Herzegovina",
    answerD: "Brazil",
    question: "In which country would you find the city of Bruges?",
  },
  {
    category: "Geography",
    correctAnswer: "The Pan American Highway",
    answerA: "The Pan American Highway",
    answerB: "Route 1",
    answerC: "The Transcontinental Road",
    answerD: "Christopher Columbus Road",
    question: "Which Road Runs From Alaska To Chile?",
  },
  {
    category: "Geography",
    correctAnswer: "Sarajevo",
    answerA: "Sarajevo",
    answerB: "Palikir",
    answerC: "Minsk",
    answerD: "Vilnius",
    question: "What is the capital city of Bosnia and Herzegovina?",
  },
  {
    category: "Geography",
    correctAnswer: "Thailand",
    answerA: "Thailand",
    answerB: "Indonesia",
    answerC: "Mongolia",
    answerD: "South Korea",
    question: "In which country is the city of Bangkok?",
  },
  {
    category: "Geography",
    correctAnswer: "Zambia",
    answerA: "Zambia",
    answerB: "Algeria",
    answerC: "Bangladesh",
    answerD: "Uzbekistan",
    question: "Lusaka is the capital city of which country?",
  },
  {
    category: "Geography",
    correctAnswer: "Red",
    answerA: "Red",
    answerB: "Orange",
    answerC: "Black",
    answerD: "Maroon",
    question: "Which of these colors would you find on the flag of Iran?",
  },
  {
    category: "Geography",
    correctAnswer: "Norway",
    answerA: "Norway",
    answerB: "Finland",
    answerC: "Sweden",
    answerD: "Denmark",
    question: "Oslo is the capital city of which country?",
  },
  {
    category: "Geography",
    correctAnswer: "Italy",
    answerA: "Italy",
    answerB: "Poland",
    answerC: "Portugal",
    answerD: "Tunisia",
    question: "Where is the Blue Grotto?",
  },
  {
    category: "Geography",
    correctAnswer: "The Danube",
    answerA: "The Danube",
    answerB: "The Nile",
    answerC: "The Amazon",
    answerD: "The Congo",
    question: "Which river has the most capital cities on it?",
  },
  {
    category: "Geography",
    correctAnswer: "Brussels",
    answerA: "Brussels",
    answerB: "Luanda",
    answerC: "Ottawa",
    answerD: "Warsaw",
    question: "What is the capital city of Belgium?",
  },
  {
    category: "Geography",
    correctAnswer: "Prague",
    answerA: "Prague",
    answerB: "Oslo",
    answerC: "Berlin",
    answerD: "Stockholm",
    question: "Which of these cities is in Czech Republic?",
  },
  {
    category: "Geography",
    correctAnswer: "Micronesia",
    answerA: "Micronesia",
    answerB: "Israel",
    answerC: "China",
    answerD: "Malawi",
    question: "Palikir is the capital city of which country?",
  },
  {
    category: "Geography",
    correctAnswer: "Galata Bridge",
    answerA: "Galata Bridge",
    answerB: "Bosphor Bridge",
    answerC: "Istanbul Suspension Bridge",
    answerD: "Topkaki Bridge",
    question: "Which Bridge Connects Europe With Asia?",
  },
  {
    category: "Geography",
    correctAnswer: "Hungary",
    answerA: "Hungary",
    answerB: "Luxembourg",
    answerC: "Moldova",
    answerD: "Greece",
    question: "In which country is the city of Budapest?",
  },
  {
    category: "Geography",
    correctAnswer: "The UK",
    answerA: "The UK",
    answerB: "Norway",
    answerC: "New Zealand",
    answerD: "South Africa",
    question:
      "In which country would you find the UNESCO World Heritage site of the Dorset and East Devon Coast?",
  },
];

const seedQuiz = async () => {
  await sequelize.sync({force: true})
  const results = await Quiz.bulkCreate(QuizData)
console.log(results);
};
seedQuiz();
